sudo: required

language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - echo "shell: $SHELL"
  - sudo apt-get -y install make
  - pip --version

install:
  - python setup.py install

script:
  - make test

