sudo: required

language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get -y install make
  - pip --version

install:
  - python setup.py -q install

script:
  - make test-app
  - make test-templates
  - make pylint


