#!/usr/bin/env bash
#    Copyright 2017 Cargill Incorporated
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Simple test that builds all example pipelines
# and does some Makefile validation

set -euo pipefail

# execute a script in its directory
function execdir {
    pushd "$(dirname $2)"
    $1 "$(basename $2)"
    popd
}

# Render all example pipelines
find examples  -name 'generate-scripts' | while read name; do
    execdir sh $name    
done

# Check example pipelines have valid Makefile targets and dependencies
find examples  -name 'test-targets.sh' | while read name; do
    execdir sh $name    
done

