#!/usr/bin/env python
#    Copyright 2017 Cargill Incorporated
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# usage: pipewrench-merge [-h] [--conf CONF] [--env ENV]
#                         [--pipeline-templates PIPELINE_TEMPLATE_DIR]
#                         [--debug_level DEBUG_LEVEL]
#
# pipewrench-merge pipeline automation tool
#
# optional arguments:
#   -h, --help            show this help message and exit
#   --conf CONF           Yaml format configuration file. This file can be used
#                         as a template to be filled by 'env.yml'
#   --env ENV             Yaml format environment file. Key-value pairs in this
#                         file that are templated in 'conf.yml'
#   --pipeline-templates PIPELINE_TEMPLATE_DIR
#                         yaml environment file
#   --debug_level DEBUG_LEVEL
#                         One of 'CRITICAL', 'WARNING', 'DEBUG', 'INFO', 'WARNING'
#
import pipewrench.merge as merge

merge.main()
