# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.5"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pylint==1.8.1
        python -m pip install pytest==3.3.1
        python -m pip install pyyaml==4.2b1
        python -m pip install jinja2==2.10.1
        python -m pip install --upgrade pip enum34 
        python setup.py -q install
        make pylint
        docker pull amfoerster/hadoop-docker
        docker pull mysql:5.7
        docker ps -a
        sudo /etc/init.d/mysql stop
        sudo apt-get -y install make
        pip --version
#    - name: Set up MySQL
#      run: |
#        sudo /etc/init.d/mysql start
#        mysql -e 'CREATE DATABASE andrew_test;' -uroot -proot
    - name: Test with pytest
      run: |
        make build
